# Generated by Django 3.0.1 on 2021-03-10 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivery_guy', models.BooleanField(default=True)),
                ('lat_long', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_long_initial', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_lat_long', models.CharField(blank=True, max_length=50, null=True)),
                ('time_spent', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_delayed', models.BooleanField(default=False)),
                ('delivery_details', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_number', models.IntegerField(default=1)),
                ('distance_travelled', models.CharField(default=0, max_length=20)),
                ('delivery_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_delivery_guy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.UserProfile')),
                ('itemdetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.ProductTable')),
            ],
        ),
    ]
