# Generated by Django 3.0.1 on 2021-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deldetails_unique_delivery_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deldetails',
            name='previous_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
